jdelb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('crearNoticia', views.crearNoticia, name="crearNoticia"),
    path('noticia/<id>', views.noticia, name="noticia"),
    path('comunas/<int:region_id>/', views.obtener_comunas, name='obtener_comunas'),
]

web/models.py
from django.db import models

# Create your models here.
class Noticia(models.Model):
    titulo = models.CharField(max_length=30, null=True)
    fecha = models.DateField(auto_now_add=True, null=True)
    descripcion = models.CharField(max_length=250, null=True)
    textoNoticia1 = models.CharField(max_length=1250, null=True)
    textoNoticia2 = models.CharField(max_length=1450, null=True, blank=True)
    imagenPreview = models.ImageField(upload_to="images", null=True, blank=True)
    imagenPrincipal = models.ImageField(upload_to="images", null=True, blank=True)
    imagenSecundaria = models.ImageField(upload_to="images", null=True, blank=True)

    class Meta:
        db_table = 'Noticia'

    def __str__(self):
        return self.titulo  
    
class Regiones(models.Model):
    nombreRegion = models.CharField(max_length=50, null=True)
    nombreCompletoDelegado = models.CharField(max_length=100, null=True)
    correoDelegado = models.CharField(max_length=150, null=True, blank=True)
    fotoDelegado = models.ImageField(upload_to="images", null=True, blank=True)
    nombreCompletoCompetidor = models.CharField(max_length=100, null=True, blank=True, default="")
    fotoCompetidor = models.ImageField(upload_to="images", null=True, blank=True)
    nombreCompletoCompetidora = models.CharField(max_length=100, null=True, blank=True, default="")
    fotoCompetidora = models.ImageField(upload_to="images", null=True, blank=True)
    imagenRegion = models.ImageField(upload_to="images", null=True)
    votos = models.IntegerField(default=0)

    class Meta:
        db_table = 'Regiones'

    def __str__(self):
        return self.nombreRegion
    
class Votaciones(models.Model):
    ip = models.GenericIPAddressField()
    nombreRegion = models.ForeignKey(Regiones, on_delete=models.PROTECT)

    class Meta:
        db_table = 'Votacion'
    
class EnVivos(models.Model):
    activar_en_vivo = models.BooleanField( default=False)
    link_transmision = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = 'EnVivos'

    def __str__(param):
        param = 'Activar Bloque en vivo'
        return param
    
class BloqueVotaciones(models.Model):
    activar_votaciones = models.BooleanField(default=False)
    class Meta:
        db_table = 'Votaciones'
    def __str__(param):
        param = 'Activar bloque votaciones'
        return param
    
class Campeones(models.Model):
    nombre_pareja = models.CharField(max_length=100, null=True)
    anno_campeon = models.CharField(max_length=5, null=True)
    foto_campeones = models.ImageField(upload_to="images", null=True)

    class Meta:
        db_table = 'Campeones'

    def __str__(self):
        return self.anno_campeon
    
class Region(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Comuna(models.Model):
    nombre = models.CharField(max_length=100)
    region = models.ForeignKey(Region, related_name='comunas', on_delete=models.PROTECT)

    def __str__(self):
        return self.nombre
    
class Inscripcion(models.Model):
    region = models.CharField(max_length=100,null=True)  # Ahora almacena el nombre en lugar del ID
    comuna = models.CharField(max_length=100, null=True)  # Ahora almacena el nombre en lugar del ID
    nombre_bailarina = models.CharField(max_length=100, null=True)
    edad_bailarina = models.PositiveIntegerField()
    fecha_nacimiento_bailarina = models.DateField()
    rut_bailarina = models.CharField(max_length=12, null=True)
    email_bailarina = models.EmailField()
    telefono_bailarina = models.CharField(max_length=15,null=True)
    nombre_bailarin = models.CharField(max_length=100,null=True)
    edad_bailarin = models.PositiveIntegerField()
    fecha_nacimiento_bailarin = models.DateField()
    rut_bailarin = models.CharField(max_length=12,null=True)
    email_bailarin = models.EmailField()
    telefono_bailarin = models.CharField(max_length=15,null=True)

    def __str__(self):
        return f"Inscripción de {self.nombre_bailarina} y {self.nombre_bailarin}"

web/templates/web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quattrocento&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    <title>Jóvenes del bicentenario</title>
</head>
<body>
    <div class="container-fluid">

        <!--Navbar-->
        <section class="row ">
          <nav class="navbar navbar-expand-md bg-dark ">
            <div id="navbar_mq" class="container-fluid ">
              <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="contenedor_navbar collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav d-flex mx-auto ">
                  <a class="nav-link text-white fw-medium" aria-current="page" href="{% url 'home' %}">Inicio</a>
                  <a class="nav-link text-white fw-medium" href="#">Nosotros</a>
                  <a class="nav-link text-white fw-medium" href="#">Organización</a>
                </div>

                {% if perms.web.add_noticia%}
                <div>
                  <a class="fw-medium btn btn-warning" href="{% url 'crearNoticia' %}">Crear Noticia para la web</a>
                </div>
                {% endif %}
              </div>
              {% if en_vivo.activar_en_vivo %}
              <img class="img-fluid logo_envivo" src="{% static 'web/img/campeonato_envivo.webp'%}" alt="en_vivo">
              {% endif %}
            </div>
          </nav>
        </section>
        <!--Fin Navbar-->

        <!--Seccion inscripción-->
        <section>
          <div>
            <!-- Button trigger modal -->


            <div class="contenedor-carrusel row ">
              <div id="carouselExampleAutoplaying" class="carousel slide ps-0 pe-0" data-bs-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <button class="px-0 mx-0 py-0 my-0" data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <img src="{% static 'web/img/banner_inscripcion.webp' %}" class="d-block w-100" alt="...">
                    </button>
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'web/img/banner_campeones.png' %}" class="d-block w-100" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            </div>



        {% block contenido_body %}
        {% endblock %}


        <div class="border-top mt-3"></div>

        <footer class="text-center">
            <div class="row pt-5 bg-dark text-white mt-5">
              <div class="col-xs-12 col-md-6 col-lg-4 ">
                <p class="h3 mt-1">Jóvenes del Bicentenario<img class="ps-4 rounded" src="{% static 'web/img/logo navbar.png'%}" alt="logo-pagina"> </p>
              </div>
              <div class="col-xs-12 col-md-4 col-lg-4 mt-4 ">
                <p class="h5">Redes sociales</p>
                <a class="me-1" href="https://www.instagram.com/jov.bicentenario/"><img src="{% static 'web/img/instagram.png' %}" alt="logo_insta"></a>
                <a class="me-1" href="https://www.facebook.com/CampeonatoJovenesDelBicentenario"><img src="{% static 'web/img/facebook.png' %}" alt="logo_face"></a>
                <a class="me-1" href="https://www.youtube.com/@jov.bicentenario"><img src="{% static 'web/img/youtube.png' %}" alt="logo_youtube"></a>
              </div>
              <div class="col-xs-12 col-md-4 col-lg-4 mt-4">
                <p class="h5">Centro de ayuda</p>
                <div>
                  <a href="" class="text-white text-decoration-none">Aviso legal</a>
                </div>
                <div>
                  <a href="" class="text-white text-decoration-none">Contacto</a>
                </div>
                {% if user.is_authenticated %}
                <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <button class="btn btn-dark text-decoration-none" type="submit">Cerrar sesión</button>
                </form>
                {% else %}
                <div>
                  <a href="{% url 'login' %}" class="text-white text-decoration-none">Acceso</a>
                </div>
                {% endif %}
              </div>              
              <div class="pt-5">
                <p class="h7 pt-5">Todos los derechos reservados Jovenes Bicentenario © </p>
                <a id="credits" href="https://portafolio-ivan-duarte.pages.dev/" class="text-decoration-none text-white pt-5">Creado por Iván Duarte Herrera</a>
              </div>
            </div>
          </footer>



        

    </div>
    
    <script src="{% static 'web/js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    <script src="{% static 'web/js/ajaxResultados.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for m in messages %}
        <script>
            Swal.fire({
                "title": "{{m}}",
                "icon": "info",
            })
        </script>
        {% endfor %}
    {% endif %}
    <script src="{% static 'web/js/scriptForm.js' %}"></script>
  </body>
</html>

web/templates/web/crearNoticia.html
{% extends 'web/base.html' %} 
{% load static %}       
{% block contenido_body %}
{% load crispy_forms_tags %}

    <section>
        <div class="text-center">
            <img  src="{% static 'web/img/banner_crear_noticia.png' %}" alt="banner_noticia">
        </div>
    </section>

    <section class="row ">
        <div class="col-5 mx-auto">
            <form action="{% url 'crearNoticia' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form | crispy }}
             
                <button type="submit" name="crear_noticia" class="btn btn-warning mt-4 w-25 ">Crear Noticia</button>
            </form>
        </div>

    </section>



{% endblock %}

web/templates/web/noticia.html
{% extends 'web/base.html' %} 
{% load static %}       
{% block contenido_body %}

    <div class="row mt-5 pt-4 mb-3">
      <div class="contenedor-titulo h-auto d-inline-block ">
        <div class="col text-center">
          <img class="img-fluid " src="{% static 'web/img/noticias_banner.png' %}" alt="event-camp">
        </div>
      </div>
    </div> 

    {% if noticia %}
    <section class="row d-flex justify-content-evenly ">
        <div class="col-12 col-md-6">
            <h1 class="fw-bold my-5">{{noticia.titulo}}</h1>
            <img class="img-fluid w-75 mt-2" src="{{ noticia.imagenPreview.url }}" alt="noticia">
            <p class="my-5 fw-medium">{{noticia.descripcion}}</p>
            <p class="my-3">{{noticia.textoNoticia1}}</p>
            {% if noticia.imagenPrincipal %}
            <img class="img-fluid my-3" src="{{ noticia.imagenPrincipal.url }}" alt="noticia">
            {% endif %}
            <p class="my-3">{{noticia.textoNoticia2}}</p>
            {% if noticia.imagenSecundaria %}
            <img class="img-fluid my-3" src="{{ noticia.imagenSecundaria.url }}" alt="noticia">
            {% endif %}
            <p>Noticia creada el {{noticia.fecha}}</p>
        </div>
        <div class="col-md-4">
            <div class="row">
                {% for news in listaNoticias %}
                <a class="col-md-6 noticia mt-5 text-black text-decoration-none" href="{% url 'noticia' news.id %}">
                  <img class="w-50 old_news" src="{{ news.imagenPreview.url }}" alt="pareja1">
                  <h4 class="fw-semibold m-0">{{news.titulo}}</h4>
                  <p class="fw-bold">{{news.fecha}}</p>
                  <div class=" d-flex flex-nowrap">
                    <p>{{news.descripcion}}</p>
                  </div>
                </a>
                {% endfor %}
              </div>
        </div>
    </section>
    {% endif %}

{% endblock %}